spring:
  application:
    name: tariff-calculator-core
  kafka:
    bootstrap-servers: ${KAFKA_HOST:172.18.0.2}:${KAFKA_PORT:9092}
    consumer:
      group-id: tf-calculator

logging:
  level:
    org: INFO
    org.lab: DEBUG
