spring:
  application:
    name: tariff-calculator-core
  kafka:
    bootstrap-servers: ${KAFKA_HOST:127.0.0.1}:${KAFKA_PORT:9092}
    consumer:
      group-id: tf-calculator

logging:
  level:
    root: WARN
    org.lab: DEBUG
