= Ejemplo de integración con Spring Integration y Apache Kafka

La aplicación contiene dos módulos que se comunican a través de una cola de Kafka. El primer módulo
será un gateway que expondrá una API REST a través de la cual recibirá las peticiones. El segundo
módulo contendrá la lógica de negocio escuchando los mensajes de una cola de Kafka utilizando para
ello Spring Integration DSL.

[source]
----
[http]        [gateway]       [kafka]      [core]        [mongo]
  |-------------->|              |           |              |
  |               |------------->| [1]       |              |
  |               |              |           |              |
  |               |              |---------->|              |
  |               |              |           |------------->|
  |               |              |<----------|              |
  |               |<-------------| [2]       |              |
  |<--------------|              |           |              |          
----

[1]: _tf-calculator-in_
[2]: _tf-calculator-out_

La información sobre cada cálculo se persistirá en mongodb, que también será utilizado para
recuperar aquella información de negocio necesaria para realizar los cálculos.


== Infraestructura localhost

Para este ejemplo utilizaremos una versión dockerizada de Kafka basada en https://hub.docker.com/r/wurstmeister/kafka/.

En primer lugar crearemos un _docker-compose.yml_ con la siguiente estructura:

[source,yml]
----
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tf-calculator-in:1:3,tf-calculator-out:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
---- 

Donde tendremos que actualizar el _KAFKA_ADVERTISED_HOST_NAME_ por la IP de nuestro bridge de docker (podemos consultarla
ejecutando el comando _docker network inspect bridge_).

Una vez estén levantados los contenedores de zookeeper y de kafka consultaremos la IP de kafka para actualizar nuestra
configuración:

[source,bash]
----
lab@lab:~/repositories/labcabrera/sample-spring-integration-kafka$ docker network ls
NETWORK ID          NAME                   DRIVER              SCOPE
5af81ac0dc0e        bridge                 bridge              local
c52e5dc6a807        host                   host                local
32a933232d33        kafka-docker_default   bridge              local
d3fb1a8b67b9        kafka_default          bridge              local
89657ae6adc9        none                   null                local
lab@lab:~/repositories/labcabrera/sample-spring-integration-kafka$ docker network inspect kafka-docker_default
[
    {
        "Name": "kafka-docker_default",
        "Id": "32a933232d331a87468a3447e9dd477b1ecfa5c511b64597700dcc2d7dffa764",
        "Created": "2018-05-22T16:13:39.118983584+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "35d55eef08f7008896076bc872640cfc33c7901aaecbdc9590c4525629e135b1": {
                "Name": "kafka-docker_kafka_1",
                "EndpointID": "c1267a2b85729d81e69a328fcb01b75ae72e6eaae720bcef234d3bd95eeabcc0",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "e45f7f873edc64110572ef5e18ec16f9e4a7af16f928a702c51806f404903449": {
                "Name": "kafka-docker_zookeeper_1",
                "EndpointID": "94c2ed61b9cb8cdbdbfaef58540491c2933b094b8e001defe9cb605abfdfa219",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
----

En este caso el valor 172.19.0.2 será el que estableceremos en nuestro yml de configuración del proyecto gateway.



----
# metodo anterior no valido por problemas de incompatibilidad de la version de kafka con la de spring
docker pull spotify/kafka
docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 --name kafka spotify/kafka
docker exec kafka /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic tf-calculator-in
docker exec kafka /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic tf-calculator-out
----

== Probando el local

En local podemos hacer una petición a la API REST para que envíe el mensaje a Kafka.

----
curl -d '{"source":"test-local"}' -H "Content-Type: application/json" http://localhost:8080/api/v1/calculator
----

https://github.com/spring-projects/spring-integration-samples/tree/master/dsl/kafka-dsl
https://github.com/labcabrera/sample-spring-kafka
https://github.com/wurstmeister/kafka-docker
